### ISSUE TITLE
Attempted import error: 'Map' is not exported from 'react-leaflet' (imported as 'LeafletMap').

### ISSUE THREAD

**Issue by reenharnoorsingh** [CleverProgrammers/react-covid-tracker#23]
![image](https://user-images.githubusercontent.com/54823204/104664323-f194c580-56f4-11eb-9d8a-22a13972528f.png)

I did it as described but still does not work for me

**Comment by Faiziimam** [comment]
use MapContainer instead Map.
import {MapContainer as LeafletMap , TileLayer} from "react-leaflet";
