### ISSUE TITLE
Graph behaves weird when select info recovered box

### ISSUE THREAD

**Issue by sohailshams** [CleverProgrammers/react-covid-tracker#24]
![recover cases graph](https://user-images.githubusercontent.com/62130176/106138970-1e24f480-616d-11eb-8a2a-b294b30e8bf3.png)
Hi Guys, when I click on recovered cased my graph goes into -ve y axis as shown in the image.  However when I click on cases and deaths it appears fine. Anyone faced the same issue ? I double checked the code with source code and it seems identical. Can anyone help to find out what is wrong here.

**Comment by Ansukun** [comment]
hey can you help me My map isnot zooming to the countries when I select the puticular coutry from menu

**Comment by sohailshams** [comment]
change your Map.js to following code;
function ChangeMapView({ coords, zoom }) {
  const map = useMap();
  map.setView([coords.lat, coords.lng], zoom);

  return null;
}

function Map({ countries, casesType, center, zoom }) {
  return (
    <div className="map">
      <LeafletMap center={center} zoom={zoom}>
        <TileLayer
          url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
          attribution='&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
        />
        <ChangeMapView coords={center} zoom={zoom} />
        {showDataOnMap(countries, casesType)}
      </LeafletMap>
    </div>
  );
}

export default Map;
and in App.js in onCountryChange add following code.
const {
          countryInfo: { lat, long },
        } = data;
        setMapCenter({ lat, lng: long });

        setMapZoom(4);

**Comment by kamal-choudhary** [comment]
Were you able to solve this issue? I am also facing the same problem.
